name: second-workflow
on: 
   workflow_dispatch:
     inputs:
        versionName:
          required : true  
          description: "this is version name for github workflow"
jobs: 
  first-workflow-job:
    name: first-job
    runs-on: ubuntu-latest      
    steps:
      - name: run bash command
        run : ls
        shell: bash 